// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmtfiuhvwgtpgaswowgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdGZpdWh2d2d0cGdhc3dvd2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODQxNzYsImV4cCI6MjA2Mzk2MDE3Nn0.ZL7LX7SNkjXDZTPveDMEY9wZhmjZ2s7fp6YbWYOibBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);